### ISSUE TITLE
你好，请删除isoftstone相关的代码及其他内容。

### ISSUE THREAD

**Issue by ChrisAaron** [yungfan/iOS-continuous-learning#2]
你好，我是软通动力集团信息安全部。通过扫描发现你的代码仓库中含有我公司相关（isoftstone）的代码等信息资产，为保证信息安全，请立刻删除下架，避免不必要的麻烦。

**Comment by yungfan** [comment]
已经删除，另外需要说明一下:
第一，本人非贵公司员工，纯属自己学习的时候从网络下载而来，里面有作者的信息，你们可以自己进行溯源。
第二，代码里面没有任何跟业务相关的逻辑代码，就是一个简单的纯知识点的使用案例，你们可以自己评估。
第三，本人没有用于非法途径，更没有从中非法获利。
